package io.github.beast3.migration;

import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.yaml.snakeyaml.Yaml;

public final class Main {

    public static void main(String[] args) throws Exception {
        Path repoRoot = locateRepoRoot();

        if (args.length > 0 && args[0].equals("report")) {
            reportMode(repoRoot, args);
        } else {
            analyzeMode(repoRoot, args);
        }
    }

    private static Path locateRepoRoot() {
        // The repo root is the directory holding packages.yaml. Walk up from
        // the current working directory until found.
        Path cwd = Paths.get("").toAbsolutePath().normalize();
        for (Path p = cwd; p != null; p = p.getParent()) {
            if (Files.isRegularFile(p.resolve("packages.yaml"))) return p;
        }
        return cwd;
    }

    private static void analyzeMode(Path repoRoot, String[] args) throws Exception {
        Path overrideRoot = null;
        for (String a : args) {
            if (a.startsWith("--")) continue;
            overrideRoot = Paths.get(a).toAbsolutePath().normalize();
            break;
        }
        if (overrideRoot != null) repoRoot = overrideRoot;

        Path config = repoRoot.resolve("packages.yaml");
        Path checklist = repoRoot.resolve("CHECKLIST.md");
        Path statusJson = repoRoot.resolve("status.json");
        Path reportsDir = repoRoot.resolve("reports");

        boolean offline = Boolean.parseBoolean(System.getProperty("offline", "false"));

        System.out.println("Analyzing packages from " + config);
        List<Report> reports = scanAll(config, repoRoot, offline);

        ChecklistWriter.write(checklist, reports);
        StatusJsonWriter.write(statusJson, reports);
        writeReports(reportsDir, reports);
        System.out.println("Wrote " + checklist);
        System.out.println("Wrote " + statusJson);
        System.out.println("Wrote " + reportsDir + "/ (" + reports.size() + " package report(s) + index)");
    }

    private static void writeReports(Path reportsDir, List<Report> reports) throws Exception {
        Files.createDirectories(reportsDir);
        StringBuilder index = new StringBuilder();
        index.append("# Per-package migration reports\n\n");
        index.append("Auto-generated by `beast3-migration-status`. Each report is a punch list\n");
        index.append("of what's left to migrate for one package, including the exact local\n");
        index.append("checkout commit it was scanned against. See [`../CHECKLIST.md`](../CHECKLIST.md)\n");
        index.append("for the high-level cross-package status table.\n\n");
        index.append("| Package | Stage | Maven Central | Local commit | Pom version |\n");
        index.append("|---|---|---|---|---|\n");
        for (Report r : reports) {
            String safe = sanitizeFilename(r.entry.name());
            Path file = reportsDir.resolve(safe + ".md");
            Files.writeString(file, PackageReportWriter.render(r));
            index.append("| [").append(r.entry.name()).append("](").append(safe).append(".md) | ")
                    .append(prettyStage(r.entry.stage())).append(" | ")
                    .append(mavenCell(r)).append(" | ")
                    .append(commitCell(r)).append(" | ")
                    .append(r.pomVersion.isBlank() ? "—" : "`" + r.pomVersion + "`").append(" |\n");
        }
        Files.writeString(reportsDir.resolve("README.md"), index.toString());
    }

    private static String sanitizeFilename(String s) {
        return s.replaceAll("[^A-Za-z0-9._-]", "_");
    }

    private static String prettyStage(String s) {
        if (s == null || s.isBlank()) return "—";
        return switch (s) {
            case "maven_central" -> "Maven Central";
            case "compile_tested" -> "compile-tested";
            case "in_progress" -> "in progress";
            case "not_started" -> "not started";
            default -> s;
        };
    }

    private static String mavenCell(Report r) {
        if (!r.entry.hasMavenCoords()) return "—";
        if (!r.mavenCentralLatest.isBlank()) return "`" + r.mavenCentralLatest + "`";
        return "❌";
    }

    private static String commitCell(Report r) {
        if (r.git.shortSha().isBlank()) return "—";
        StringBuilder s = new StringBuilder("`").append(r.git.shortSha()).append("`");
        if (r.git.dirty()) s.append(" *(dirty)*");
        return s.toString();
    }

    private static void reportMode(Path repoRoot, String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("Usage: report <package-name> [--out <file>]");
            System.exit(2);
            return;
        }
        String pkgName = args[1];
        Path out = null;
        for (int i = 2; i < args.length; i++) {
            if (args[i].equals("--out") && i + 1 < args.length) {
                out = Paths.get(args[++i]);
            }
        }

        Path config = repoRoot.resolve("packages.yaml");
        boolean offline = Boolean.parseBoolean(System.getProperty("offline", "false"));

        List<PackageEntry> entries = loadConfig(config, repoRoot);
        PackageEntry entry = entries.stream()
                .filter(e -> e.name().equalsIgnoreCase(pkgName))
                .findFirst()
                .orElse(null);
        if (entry == null) {
            System.err.println("Unknown package: " + pkgName);
            System.err.println("Tracked packages:");
            for (PackageEntry e : entries) System.err.println("  " + e.name());
            System.exit(2);
            return;
        }

        Report r = scanOne(entry, offline);
        String text = PackageReportWriter.render(r);
        if (out != null) {
            Files.writeString(out, text);
            System.err.println("Wrote " + out.toAbsolutePath());
        } else {
            System.out.print(text);
        }
    }

    private static List<Report> scanAll(Path config, Path repoRoot, boolean offline) throws Exception {
        List<PackageEntry> entries = loadConfig(config, repoRoot);
        System.out.println("Found " + entries.size() + " package(s).");
        MavenCentralProbe probe = new MavenCentralProbe();
        List<Report> reports = new ArrayList<>();
        for (PackageEntry e : entries) {
            System.out.println("  - " + e.name() + " (" + e.path() + ")");
            reports.add(scan(e, probe, offline));
        }
        return reports;
    }

    private static Report scanOne(PackageEntry entry, boolean offline) {
        return scan(entry, new MavenCentralProbe(), offline);
    }

    private static Report scan(PackageEntry entry, MavenCentralProbe probe, boolean offline) {
        Report r = new Report(entry);
        r.pathExists = Files.isDirectory(entry.path());
        if (r.pathExists) {
            r.git = GitInfo.read(entry.path());
            JavaScanner.scan(entry.path(), r);
            JavaScanner.resolveAndTally(r);
            XmlScanner.scan(entry.path(), r);
            BuildScanner.scan(entry.path(), r);
        } else {
            r.error = "local path missing";
        }
        if (!offline) probe.probe(r);
        return r;
    }

    @SuppressWarnings("unchecked")
    private static List<PackageEntry> loadConfig(Path config, Path repoRoot) throws Exception {
        Yaml yaml = new Yaml();
        try (Reader r = Files.newBufferedReader(config)) {
            Map<String, Object> root = yaml.load(r);
            List<Map<String, Object>> raw = (List<Map<String, Object>>) root.get("packages");
            List<PackageEntry> out = new ArrayList<>();
            for (Map<String, Object> m : raw) out.add(PackageEntry.from(m, repoRoot));
            return out;
        }
    }
}
